language: python
python:
- '3.6'
sudo: enabled
addons:
  apt:
    packages:
    - liblapack-dev
    - libopenmpi-dev
    - openmpi-bin
    - libhdf5-serial-dev
    - gfortran
install:
- source continuous_integration/install.sh
- pip install matplotlib
- pip install LFPy>=2.1
- pip install .
- pip install pytest
- pip install pytest-cov
- pip install coverage
- pip install coveralls
script: pytest --cov=MEArec/ --cov-config .coveragerc -s
after_success:
  - coveralls
deploy:
  provider: pypi
  user: alejoe91
  on:
    branch: master
    tags: true
  password:
    secure: efg8Q0UmMUG5YWEh7N0/FJuy9zu1Gq/UgxX7J5dmZN+uRvw4eLuwOOrdew5oNtC06oKRlD2k5spfEsm/rfoRqopnlsrYnxx08ib903incRJiFZzpSl9dJEkQ8V74aN8tjjtylwPtooXGJwziv+oryYzb4i4Vga1wf1D6umd4EU5eG7VSH1FLRot081AjfrRPu7FB2mZ/TiYnS3L4oSHrGuQLcVywCMsNVxXP4uZVR6GjUGAgrcwlCtvi/lg+YTRTVeBqDU5EXSm12d5wmbp/YET9BcfBhSkzgSSwzRHYOa4+XR8ZNzyy5uqIQmmaZlEnc+452j3MNtk9X7K4bqOs3b1WwN7xJyqvGD9gQr+ow/o/wqjDayeu0gATZsPhH46K8+7jbEKpy03FtxU6HnswPBqklExHo/wF0S30ZTqeMPsNKqYgX22UG57HIkmuX6Ym5s+b58imBb7grYELl9AeXYrtU9YrvEXVgBDOr5BhJHlcGZ5ic7rrvisnfLr8KNP0LhFLPzaBfi3GN5ETDA458zAvtWrwWLC4lnJZqFdtxL6HEwr0E+K+3Qqzr7iLeupaDiEVNZrw5hlanFUN3Ret17tGFc8eIm0gqzCECROvJrd2yjwvqQEuWRreW374P7/NOWU8I28B5xhMa6YGGORNqXDVYBi9r8k+CCf6tFfBYmg=
